### ISSUE TITLE
New ID format for some in 2021

### ISSUE THREAD

**Issue by fifieldt** [enylin/taiwan-id-validator#12]
Starting January 2, 2021 a new ID number format will be introduced for:
* Taiwan Nationals without Household Registration
* Hong Kong/Macao/Mainland Residents
* Foreign Residents

the old number format will also remain in place for up to 10 years

Details of the new format and reason for the change at:

https://www.immigration.gov.tw/5382/5385/7445/238440/238442/241508/

https://www.immigration.gov.tw/5385/7445/238440/238442/240309/

**Comment by fifieldt** [comment]
Official schema was updated:

https://schema.gov.tw/Commonality/Commonality/Common%20Data

**Comment by enylin** [comment]
Thanks. Feature implemented.
