### ISSUE TITLE
Reference Error: self is not defined

### ISSUE THREAD

**Issue by ARui-TW** [enylin/taiwan-id-validator#19]
Using Vue and Nuxt on version 1.3. (Version 1.2 will work somehow.)
![image](https://user-images.githubusercontent.com/66272957/132949663-66aedb82-d2d2-4bf8-a38f-fc27b1e9b6fa.png)

**Comment by enylin** [comment]
I just tried the v1.3 package with a newly created Nuxt app (created with create-nuxt-app v3.7.1.)
It worked just fine.

I created the app with the following config:
```
Programming language: TypeScript
Package manager: Npm
UI framework: None
Nuxt.js modules: (Press <space> to select, <a> to toggle all, <i> to invert selection)
Linting tools: ESLint, Prettier, Lint staged files, StyleLint, Commitlint
Testing framework: Jest
Rendering mode: Single Page App
Deployment target: Static (Static/Jamstack hosting)
Development tools: jsconfig.json (Recommended for VS Code if you're not using typescript)
Continuous integration: None
Version control system: Git
```

Can you reproduce the error using online IDE? Something like JS Fiddle, Codesandbox
It'll be helpful if you can provide any further details.
