### ISSUE TITLE
營利事業統一編號檢查碼邏輯修正說明

### ISSUE THREAD

**Issue by danny-source** [enylin/taiwan-id-validator#21]
「檢查邏輯由可被『10』整除改為可被『5』整除」
[營利事業統一編號檢查碼邏輯修正說明](
https://www.fia.gov.tw/singlehtml/6?cntId=aaa97a9dcf2649d5bdd317f554e24f75)

**Comment by Liya210502** [comment]
你好，這邊好像有點兒問題~ @enylin 


![image](https://github.com/enylin/taiwan-id-validator/assets/169115732/ffcc50c3-f2f7-4f4a-8f36-74103999d704)

官方文件截圖
![image](https://github.com/enylin/taiwan-id-validator/assets/169115732/48dc5222-dce2-4331-ac3e-1011bc639162)
![image](https://github.com/enylin/taiwan-id-validator/assets/169115732/0ec84eed-b57c-4107-926a-0d19500cd8bd)

ref
https://www.fia.gov.tw/singlehtml/3?cntId=c4d9cff38c8642ef8872774ee9987283

**Comment by enylin** [comment]
@Liya210502 您可以傳入第二個參數 (true) 使用新版統一編號驗證功能。
例如：
```ts
console.log(isGuiNumberValid('04595252', true)) // 新版統一編號
```

過去第一版開發的時候，政府公告的計算方式是除以 10 而非除以 5 來驗證正確性，因此我們以此公式開發軟體。
2021 年時政府公告新版統一編號計算方式，但實施時間是 2023 年，所以當時不適合把公式直接改為除以 5，避免將錯誤的統一編號驗證為正確的統一編號。
當時程式因應的作法是在後面加上一個 optional 的參數並預設為使用舊版公式驗證，這樣使用者可以自由選擇是否使用新的公式驗證，同時避免套件產生 breaking change。

我現在正在開發第二版，推出的時候會修改成預設使用新版公式，避免使用者產生困擾。
