### ISSUE TITLE
使用 console.error 在 React native 開發時會發生問題

### ISSUE THREAD

**Issue by bob76828** [enylin/taiwan-id-validator#3]
可以將 console.error 換成 console.log 或其他的嗎？
在RN開發時，會被 console.error 的訊息覆蓋，開發體驗蠻糟的。

![螢幕快照 2019-08-28 下午4 15 24](https://user-images.githubusercontent.com/7965939/63838007-1c229900-c9af-11e9-9846-5c1ef9063c09.png)

**Comment by doggy8088** [comment]
@bob76828 作者好像沒在維護了，我今天 fork 了一份，已經移除所有 try/cache 與 throw new Error 的代碼，也重新發布新的套件為 [taiwan-id-validator2](https://www.npmjs.com/package/taiwan-id-validator2)，你可以試試看。 Repo: https://github.com/doggy8088/taiwan-id-validator2/

**Comment by enylin** [comment]
已修正 59a0ce637e277493009e22913da008f8f9cef03b
