### ISSUE TITLE
About中寫錯啦，不是“中華民國”

### ISSUE THREAD

**Issue by zelihole** [enylin/taiwan-id-validator#36]
中華民國已經不復存在了，現在的中國只有中華人民共和國。
你可以說“臺灣省”、“台灣地區”、“台灣特別行政區”。
PRC

**Comment by enylin** [comment]
感謝你的回應和意見。這個專案的目標是為了提供一個可靠的方法來驗證「中華民國」身分證字號，這是目前在台灣使用的官方身分證件，並由中華民國政府所頒發。使用「中華民國」這個名稱，並不是出於政治立場或意識形態，而是因為這是此證件的官方名稱。
這是一個開源專案，任何人都可以自由地 fork 並修改。如果你對專案的某些部分有不同的看法，你完全有權利修改並發布自己的版本。
我們明白你的關注點，但請了解這個專案的目的並不在於政治辯論，而是提供一個技術性的解決方案。我們希望在這個平台上，能夠維持對技術的專注和討論。再次感謝你的評論。
