### ISSUE TITLE
統一編號 有些判斷不出來

### ISSUE THREAD

**Issue by rockmandash** [enylin/taiwan-id-validator#37]
無法判斷的有這些，已經用 `taiwanIdValidator.isGuiNumberValid(item.id, true)` 還是不行，不知道是不是 edge case：

我放在 gist 因為檔案太大： https://gist.github.com/rockmandash/6acd69c37d9cc0ca92b276b53b25f4be

**Comment by Mowd** [comment]
因為統編規則有更新，加入第七位7的判斷以及除以五
https://www.fia.gov.tw/singlehtml/3?cntId=c4d9cff38c8642ef8872774ee9987283

**Comment by enylin** [comment]
您好，我有看 gist 裡面的統編資料了。我有對其中一些查詢驗證，發現裡面有些統編的格式不是現行接受的格式。

舉例來說，資料裡面第一筆「臺保實業有限公司」，顯示的統編是：A0342336，統編裡面不應該出現英文字母。
再來是第二筆「豪強企業有限公司」，顯示的統編是：90316313，到財政部的[稅籍登記資料](https://www.etax.nat.gov.tw/etwmain/etw113w1/ban/query)上查詢，可以發現它顯示「統一編號格式有誤」。

建議您可以先驗證統編的資料來源，若有其他問題也歡迎再提出討論。

**Comment by enylin** [comment]
豪強企業有限公司（90316313）是登記在臺中市東勢區，今天早上已致電台中市政府經濟發展局，他們回覆確認這筆資料跟他們系統裡面查到的是符合的，他們也協助查詢臺保實業有限公司（A0342336）的資料也與他們系統內的資料相符。他們推測英文開頭的統編是較早期留下來的號碼。
另外也查到臺保實業有限公司現在統編是 76408393，推測是統編已變更。

今天早上也已致電詢問財政部財政資訊中心曾先生關於經濟部開放資料與統一編號檢查碼邏輯不符事宜，對方回覆可以協助我們進一步詢問經濟部，待對方回覆後我再把資訊更新上來。

**Comment by enylin** [comment]
經濟部商業發展署有回覆了，他們查詢到的系統資料如下：

- [豪強企業有限公司] 統一編號：90316313，登記機關為臺中市政府經發局。
- [臺保實業有限公司] 無統一編號，該筆資料並不完整。可能為[台保實業有限公司]，統一編號：76408393 登記機關為高雄市政府經濟發展局。
- [珍倪生技有限公司] 112年4月公司設立登記所營事業項目清冊，共有2筆統一編號：93778639、41050981。登記機關為高雄市政府經濟發展局

後來我也有跟相關人員討論，英文字母開頭的統編應該是早期的統編的格式沒有轉換，編號不符合規則的統一編號可能是發號的過程有錯誤，例如抄寫錯誤。公司若認為自己的統一編號有問題，是可以申請變更的，因此會看到有些公司有新的統一編號，這些新的統一編號應該都是符合規則的。
