### ISSUE TITLE
台灣外僑及大陸人士在臺居留證字號有新版規則

### ISSUE THREAD

**Issue by doggy8088** [enylin/taiwan-id-validator#7]
台灣外僑及大陸人士在臺居留證字號有[新版的規則](https://law.fsc.gov.tw/law/NewsContent.aspx?id=7914)，自民國110年起(明年)新換發的第二個字不會是英文字，如果有用到居留證字號的驗證需留意！

![image](https://user-images.githubusercontent.com/88981/76729459-3037b780-6794-11ea-934f-90984f8a92a9.png)

119年之前，新舊制並存

![image](https://user-images.githubusercontent.com/88981/76729361-f1096680-6793-11ea-80f4-338e93f30db9.png)

**Comment by enylin** [comment]
謝謝提供！已實作新功能
