### ISSUE TITLE
能否不要以throw Error的方式來提供驗證失敗的情況

### ISSUE THREAD

**Issue by dcvsling** [enylin/taiwan-id-validator#8]
驗證失敗不是例外錯誤 而是預期的結果 (是的 預期他可能會失敗)
使用Throw 可能會導致使用時真的讓使用者感受到無法預期的錯誤發生 而不是驗證失敗的結果
這導致使用方可能被迫再使用的時候得仰賴 catch 來捕捉失敗的驗證
我個人認為 其實只需要建立一個 result 的 interface
例如 像是這樣
```typescript
export interface ValidateResult {
    source: string;
    isValid: boolean;
    failReason: string;
}
```
你可以再透過一個快速產生結果的做法來完成他 例如
```typescript
export namespace ValidateResult {
   export Success(source: string): ValidateResult {
      return {
         source,
         isValid: true,
         failReason: ''
      };
   }
   export Fail(source: string, failReason: string): ValidateResult {
       return {
           source,
           isValid: false,
           failReason,
       }
   }
}
```
另外, 通常如果我們在驗證上透過例外的方式來呈現的方法名稱是 ensure
ensure的意思是請保證他符合預期 那麼此時 驗證失敗就是不符合預期的事情
那麼此時再使用 throw Error 來處理驗證失敗的情況 
並且再方法回傳時回傳要被驗證的值 
讓使用方可以像是回到還沒調用驗證錢的情況下繼續接下來的處理

以上僅建議 如果有不清楚想釐清的部分 也可以討論 
我沒有急著想要這些功能 (如果有我就fork or pull request了)
所以只是想提供意見而已

**Comment by zhuangya** [comment]
@dcvsling Kevin 我觉得你说的有一定的道理

但是如果换个角度来看呢？如果这个 validation 返回的结果是 boolean
那么是不是只返回 `true` / `false` 就可以了呢？

另外一方面，你提议的 `ValidateResult` 中的 `failReason` 应该是 optional 才对，毕竟通过验证的结果是不需要这个 `failReason` 的。

再，我觉得对于应用 validator 的程序来说，可能会更期望从业务的角度来填写这个 reason 是什么，而不是 validator 返回一个非常冰冷的 `failReason`

我觉得可以稍微改一下 validator 返回的结果，让它直接只返回 boolean 在我看来是比较合理的做法。

**Comment by dcvsling** [comment]
如果你有想法的話當然是更好 我只是做一個提議
畢竟直接throw error 真的太硬了
而且我也希望有更多的討論來決定這件事情

**Comment by doggy8088** [comment]
其實也不應該直接輸出 `console.error()`

![image](https://user-images.githubusercontent.com/88981/84664009-7eee1c80-af50-11ea-97f8-8b0ab78f737c.png)

**Comment by doggy8088** [comment]
作者好像沒在維護了，我今天 fork 了一份，已經移除所有 try/cache 與 throw new Error 的代碼，也重新發布新的套件為 [taiwan-id-validator2](https://www.npmjs.com/package/taiwan-id-validator2)。

**Comment by enylin** [comment]
已修正 59a0ce637e277493009e22913da008f8f9cef03b
